const applicantsData = [
  {
    name: "Shahwaiz",
    contactnumber: "+923316281250",
    city: "Gujrat",
    country: "Pakistan",
    password: "secret",
    email: "shahwaiz@gmail.com",
  },
  {
    name: "Safi Maaz",
    contactnumber: "+923316281250",
    city: "Gujrat",
    country: "Pakistan",
    qualifications: "BSCS",
    experience: "Over-Qualified",
    desiredJob: "CEO at Google",
    description: "I'll only work as part-time",
    password: "secret",
    email: "Safi@gmail.com",
  },
  {
    name: "Abdullah Maaz",
    contactnumber: "+923316281250",
    city: "Gujrat",
    country: "Pakistan",
    qualifications: "BSCS",
    experience: "Over-Qualified",
    desiredJob: "CEO at Google",
    description: "I'll only work as part-time",
    password: "secret",
    email: "Abdullah@gmail.com",
  },
  {
    name: "Armaan",
    contactnumber: "+923316281250",
    city: "Gujrat",
    country: "Pakistan",
    qualifications: "BSCS",
    experience: "Over-Qualified",
    desiredJob: "CEO at Google",
    description: "I'll only work as part-time",
    password: "secret",
    email: "Armaan@gmail.com",
  },
  {
    name: "Faizan",
    contactnumber: "+923316281250",
    city: "Gujrat",
    country: "Pakistan",
    qualifications: "BSCS",
    experience: "Over-Qualified",
    desiredJob: "CEO at Google",
    description: "I'll only work as part-time",
    password: "secret",
    email: "Faizan@gmail.com",
  },
  {
    name: "Amjad",
    contactnumber: "+923316281250",
    city: "Gujrat",
    country: "Pakistan",
    qualifications: "BSCS",
    experience: "Over-Qualified",
    desiredJob: "CEO at Google",
    description: "I'll only work as part-time",
    password: "secret",
    email: "Amjad@gmail.com",
  },
  {
    name: "Subhan",
    contactnumber: "+923316281250",
    city: "Gujrat",
    country: "Pakistan",
    qualifications: "BSCS",
    experience: "Over-Qualified",
    desiredJob: "CEO at Google",
    description: "I'll only work as part-time",
    email: "Subhan@gmail.com",
    password: "secret",
  },
  {
    name: "Jawad",
    contactnumber: "+923316281250",
    city: "Gujrat",
    country: "Pakistan",
    qualifications: "BSCS",
    experience: "Over-Qualified",
    desiredJob: "CEO at Google",
    description: "I'll only work as part-time",
    password: "secret",
    email: "Jawad@gmail.com",
  },
  {
    name: "Zeeshan",
    contactnumber: "+923316281250",
    city: "Gujrat",
    country: "Pakistan",
    qualifications: "BSCS",
    experience: "Over-Qualified",
    desiredJob: "CEO at Google",
    description: "I'll only work as part-time",
    password: "secret",
    email: "Zeeshan@gmail.com",
  },
  {
    name: "Arif",
    contactnumber: "+923316281250",
    city: "Gujrat",
    country: "Pakistan",
    qualifications: "BSCS",
    experience: "Over-Qualified",
    desiredJob: "CEO at Google",
    description: "I'll only work as part-time",
    password: "secret",
    email: "Arif@gmail.com",
  },
];
const recruitersData = [
  {
    name: "Shahwaiz",
    contactnumber: "+923316281250",
    companyName: "Gujrat",
    logo: "Pakistan",
    password: "secret",
    email: "shahwaiz@gmail.com",
  },
  {
    name: "Safi Maaz",
    contactnumber: "+923316281250",
    companyName: "Gujrat",
    logo: "Pakistan",
    password: "secret",
    email: "Safi@gmail.com",
  },
  {
    name: "Abdullah Maaz",
    contactnumber: "+923316281250",
    companyName: "Gujrat",
    logo: "Pakistan",
    password: "secret",
    email: "Abdullah@gmail.com",
  },
  {
    name: "Armaan",
    contactnumber: "+923316281250",
    companyName: "Gujrat",
    logo: "Pakistan",
    password: "secret",
    email: "Armaan@gmail.com",
  },
  {
    name: "Faizan",
    contactnumber: "+923316281250",
    companyName: "Gujrat",
    logo: "Pakistan",
    password: "secret",
    email: "Faizan@gmail.com",
  },
  {
    name: "Amjad",
    contactnumber: "+923316281250",
    companyName: "Gujrat",
    logo: "Pakistan",
    password: "secret",
    email: "Amjad@gmail.com",
  },
  {
    name: "Subhan",
    contactnumber: "+923316281250",
    companyName: "Gujrat",
    logo: "Pakistan",
    password: "secret",
    email: "Subhan@gmail.com",
  },
  {
    name: "Jawad",
    contactnumber: "+923316281250",
    companyName: "Gujrat",
    logo: "Pakistan",
    password: "secret",
    email: "Jawad@gmail.com",
  },
  {
    name: "Zeeshan",
    contactnumber: "+923316281250",
    companyName: "Gujrat",
    logo: "Pakistan",
    password: "secret",
    email: "Zeeshan@gmail.com",
  },
  {
    name: "Arif",
    contactnumber: "+923316281250",
    companyName: "Gujrat",
    logo: "Pakistan",
    password: "secret",
    email: "Arif@gmail.com",
  },
  {
    name: "Hassan",
    contactnumber: "+923316281250",
    companyName: "Gujrat",
    logo: "Pakistan",
    password: "secret",
    email: "Hassan@gmail.com",
  },
];

module.exports = {
  applicantsData,
  recruitersData,
};
